import { AppUser, Transaction } from '../types';



export let mockUsers: AppUser[] = [
  {
    id: 'usr_1',
    name: 'Abebe Kebede',
    email: 'abebe@chapa.co',
    role: 'user',
    active: true,
  },
  {
    id: 'usr_2',
    name: 'Helen Tekle',
    email: 'helen@chapa.co',
    role: 'user',
    active: true,
  },
  {
    id: 'usr_3',
    name: 'Dawit Assefa',
    email: 'dawit@chapa.co',
    role: 'user',
    active: false, // Starts disabled to test the Activate toggle
  },
  {
    id: 'usr_4',
    name: 'Tigist Girma',
    email: 'tigist@chapa.co',
    role: 'user',
    active: true,
  },
  {
    id: 'usr_5',
    name: 'Yared Hailu',
    email: 'yared@chapa.co',
    role: 'admin',
    active: true,
  },
  {
    id: 'usr_6',
    name: 'Martha Demissie',
    email: 'martha@chapa.co',
    role: 'admin',
    active: true,
  },
  {
    id: 'usr_7',
    name: 'Solomon Berhanu',
    email: 'solomon@chapa.co',
    role: 'super_admin',
    active: true,
  },
  {
    id: 'usr_8',
    name: 'Bethlehem Tsegaye',
    email: 'bethel@chapa.co',
    role: 'user',
    active: true,
  },
];

export let mockTransactions: Transaction[] = [
  {
    id: 'tx_1',
    userEmail: 'abebe@chapa.co',
    amount: 2500,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-10T14:30:00Z',
    tx_ref: 'tx-abebe-001',
  },
  {
    id: 'tx_2',
    userEmail: 'abebe@chapa.co',
    amount: 5000,
    currency: 'ETB',
    status: 'pending',
    date: '2026-07-11T09:15:00Z',
    tx_ref: 'tx-abebe-002',
  },
  {
    id: 'tx_3',
    userEmail: 'helen@chapa.co',
    amount: 12000,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-09T18:45:00Z',
    tx_ref: 'tx-helen-001',
  },
  {
    id: 'tx_4',
    userEmail: 'helen@chapa.co',
    amount: 1500,
    currency: 'ETB',
    status: 'failed',
    date: '2026-07-08T11:20:00Z',
    tx_ref: 'tx-helen-002',
  },
  {
    id: 'tx_5',
    userEmail: 'dawit@chapa.co',
    amount: 750,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-05T16:00:00Z',
    tx_ref: 'tx-dawit-001',
  },
  {
    id: 'tx_6',
    userEmail: 'tigist@chapa.co',
    amount: 8900,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-11T12:00:00Z',
    tx_ref: 'tx-tigist-001',
  },
  {
    id: 'tx_7',
    userEmail: 'bethel@chapa.co',
    amount: 3100,
    currency: 'ETB',
    status: 'pending',
    date: '2026-07-12T08:00:00Z',
    tx_ref: 'tx-bethel-001',
  },
  {
    id: 'tx_8',
    userEmail: 'abebe@chapa.co',
    amount: 450,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-06T10:30:00Z',
    tx_ref: 'tx-abebe-003',
  },
  {
    id: 'tx_9',
    userEmail: 'helen@chapa.co',
    amount: 6200,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-07T14:22:00Z',
    tx_ref: 'tx-helen-003',
  },
  {
    id: 'tx_10',
    userEmail: 'tigist@chapa.co',
    amount: 12500,
    currency: 'ETB',
    status: 'failed',
    date: '2026-07-06T09:12:00Z',
    tx_ref: 'tx-tigist-002',
  },
  {
    id: 'tx_11',
    userEmail: 'bethel@chapa.co',
    amount: 9500,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-10T17:50:00Z',
    tx_ref: 'tx-bethel-002',
  },
  {
    id: 'tx_12',
    userEmail: 'abebe@chapa.co',
    amount: 15000,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-03T11:00:00Z',
    tx_ref: 'tx-abebe-004',
  },
  {
    id: 'tx_13',
    userEmail: 'helen@chapa.co',
    amount: 3500,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-04T13:45:00Z',
    tx_ref: 'tx-helen-004',
  },
  {
    id: 'tx_14',
    userEmail: 'tigist@chapa.co',
    amount: 4200,
    currency: 'ETB',
    status: 'pending',
    date: '2026-07-12T07:10:00Z',
    tx_ref: 'tx-tigist-003',
  },
  {
    id: 'tx_15',
    userEmail: 'dawit@chapa.co',
    amount: 1800,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-01T15:20:00Z',
    tx_ref: 'tx-dawit-002',
  },
  {
    id: 'tx_16',
    userEmail: 'bethel@chapa.co',
    amount: 600,
    currency: 'ETB',
    status: 'failed',
    date: '2026-06-30T10:05:00Z',
    tx_ref: 'tx-bethel-003',
  },
  {
    id: 'tx_17',
    userEmail: 'abebe@chapa.co',
    amount: 7800,
    currency: 'ETB',
    status: 'success',
    date: '2026-07-02T16:40:00Z',
    tx_ref: 'tx-abebe-005',
  },
];
